source "http://rubygems.org"

eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))

# Declare your gem's dependencies in leap_web_users.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# To use debugger
# gem 'ruby-debug'
