services:
  - couchdb
notifications:
  email: false
before_script:
  - "test/setup_couch.sh"
  - "mv test/config/couchdb.yml.admin config/couchdb.yml"
  - "bundle exec rake couchrest:migrate_with_proxies"
  - "bundle exec rake couchrest:migrate_with_proxies"  # looks like this needs to run twice
  - "mv test/config/couchdb.yml.user config/couchdb.yml"
