# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "LEAP/wheezy"

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.auto_detect = true
  end

  config.vm.synced_folder "..", "/leap_web"
  config.vm.network "forwarded_port", guest: 3000, host: 3000

  config.vm.provision :puppet do |puppet|
    puppet.manifest_file = "development.pp"
    puppet.module_path = ["modules"]
  end

    config.vm.provision :shell, :run => 'always', :privileged => false, :inline => <<-SCRIPT
      cd /leap_web && bundle --binstubs && rake db:rotate db:migrate
    SCRIPT
end
