source "https://rubygems.org"

eval(File.read(File.dirname(__FILE__) + '/../common_dependencies.rb'))
eval(File.read(File.dirname(__FILE__) + '/..//ui_dependencies.rb'))

# We require leap_web_core from here so we can use the path option.
gem "leap_web_core", :path => '../core'

# Declare your gem's dependencies in leap_web_users.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

# To use debugger
# gem 'ruby-debug'
